apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
        updated: "true"  # If you want to use this label for some purpose
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
